name: Check standards

on:
  push:
    branches: [ development, production ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ development ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        os: [ubuntu-20.04]
        wordpress: [6.0.2, latest]
        experimental: [false]
        include:
          - php: 8.0
            os: ubuntu-20.04
            wordpress: latest
            experimental: true
    name: Test - PHP ${{ matrix.php }} - WP ${{ matrix.wordpress }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ matrix.php }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: pcov

      - name: Install PHP dependencies
        run: |
          export PATH="$HOME/.composer/vendor/bin:$PATH"
          composer install --no-interaction

      - name: Run php-cs-fixer
        run: composer standards
