name: Tests

on:
  push:
    branches: [ development, staging, production ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ development, staging, production ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        os: [ubuntu-20.04]
        wordpress: [6.0.2, latest]
        experimental: [false]
#        include:
#          - php: 8.0
#            os: ubuntu-20.04
#            wordpress: latest
#            experimental: true

    name: Test - PHP ${{ matrix.php }} - WP ${{ matrix.wordpress }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start required services
        run: sudo systemctl start mysql.service

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ matrix.php }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: pcov

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress

      - name: Install WP tests
        run: bash install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress }}

      - name: Run PHP Tests
        run: composer test
        if: matrix.experimental == true

      - name: Run PHP Tests with coverage
        run: composer test-coverage
        if: matrix.experimental == false

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.experimental == false
